## first question

text = "ACTGTCAGTTTTCTGTCAGCCTGTCAGTTGACTGTCAGGCTGAAGCTGTCAGACATTCTGTCAGGTGTGCTGTCAGTTTGCTGTCAGCCTGTCAGCACTGTCAGCACTGTCAGCTGTCAGCCTGTCAGGCTGTCAGCTGTCAGCTGTCAGCCTCTGTCAGTTCCTGGGGTAGCCCCTGTCAGCGCTGTCAGAACGCTGTCAGCTGTCAGGCTGTCAGCTGTCAGTCCTGTCAGGGTCTGTCAGCCTGTCAGCCACTGTCAGGAGCCTGTCAGCTGTCAGGCTGTCAGACCTCTGTCAGTTGGAGAGTACCGTCTCACTGTCAGTTTTCTGTCAGCTGTCAGAGGAGAGCCTGCTGTCAGCAAGAGACACTGCAGTTCTGTCAGCTGTCAGCTGTCAGCTGTCAGCTGGCTGTCAGCTGTCAGGCCTCCTGTCAGCTGTCAGTGGCCTGTCAGCTGTCAGTAATGTTCCCGACCTGTCAGCCTGTCAGATTGACTGTCAGTACTGTCAGCTGTCAGGATCTGTCAGTCTGTCAGAGACCAACGGTCCGACACTGTCAGCTGTCAGCTGTCAGATGAATCTGTCAGGCTGTCAGAATCCTGTCAGCTGTCAGACAAAAGCCCCCTGTCAGCTGTCAGCTGTCAGCTGTCAGGCTCTGTCAGCTCTGTCAGACTGTCAGCTGTCAGGTAACTGTCAGCTGTCAGGAGCTGTCAGCTGTCAGGCTGTCAGCACCTGTCAGGGCCCACTGTCAGGCTGTCAGAGTTCCTGTCAGAGACCTGTCAGATCTGTCAGCTGTCAGACTGTCAGCTGTCAGGCTGTCAGCTGTCAGCTACCTGTCAGCTGTCAGAAACCCAACACCTGTCAGTCTGTCAGGCTGTCAGGACTGTCAGCTGTCAGCTGTCAGTCTCTGTCAGCTGTCAGCTGTCAGTTCTGTCAGAC"
pattern = "CTGTCAGCT"

def patternCount(text, pattern):
    count = 0
    for i in range(len(text) - len(pattern)):
        print(text[i:i + len(pattern)])
        if(text[i:i+len(pattern)] == pattern):
            count = count + 1
    return count

print(patternCount(text, pattern))

## second question

text = "CGGCGACGTGACAACCTAGCAATGTGACAACGTGACAACCTAGCAATCAATCGTAGGTGACAACCGGCGACGAAATAGGTCGGCGACCTAGCAATCAATCGTAGCGGCGACGTGACAACGTGACAACCAATCGTAGGAAATAGGTCTAGCAATGAAATAGGTGAAATAGGTGTGACAACCGGCGACCTAGCAATGAAATAGGTGAAATAGGTCAATCGTAGCTAGCAATGAAATAGGTCAATCGTAGGTGACAACCAATCGTAGCAATCGTAGGTGACAACCAATCGTAGCGGCGACGTGACAACCTAGCAATCGGCGACCAATCGTAGGAAATAGGTGAAATAGGTCAATCGTAGCGGCGACCGGCGACCAATCGTAGGAAATAGGTCTAGCAATCGGCGACCAATCGTAGCGGCGACCAATCGTAGCTAGCAATCGGCGACCAATCGTAGCGGCGACGAAATAGGTGTGACAACGAAATAGGTCAATCGTAGGTGACAACGTGACAACGTGACAACCTAGCAATGTGACAACCGGCGACCAATCGTAGCAATCGTAGGAAATAGGTCTAGCAATGTGACAACGAAATAGGTGAAATAGGTGTGACAACGTGACAACCGGCGACCAATCGTAGGTGACAACGAAATAGGTCGGCGACGTGACAACCTAGCAATGAAATAGGTGAAATAGGTCGGCGACGTGACAACCTAGCAATCTAGCAATCAATCGTAGCAATCGTAGGAAATAGGTCAATCGTAGGTGACAACGAAATAGGTGTGACAACGTGACAACCGGCGACCAATCGTAG"

def frequency(text, k):
    dictionary = {}
    max = 0;
    finalString = "";
    for i in range(len(text) - k):
        key = text[i:i+k]
        if key in dictionary:
            dictionary[key] = dictionary[key] + 1
        else:
            dictionary[key] = 1
    
        if dictionary[key] > max:
            max = dictionary[key]

    for key, value in dictionary.items():
        if(value == max):
            finalString = finalString + key + " "

    print(max)
    return (finalString.strip(), max)
        

print(frequency(text, 11))